# Generated by Django 5.2.4 on 2025-10-19 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_note_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(help_text='Chat session title', max_length=200),
                ),
                (
                    'course_data',
                    models.JSONField(
                        blank=True,
                        help_text='JSON data for the course being tutored',
                        null=True,
                    ),
                ),
                (
                    'avatar_id',
                    models.CharField(
                        blank=True,
                        help_text='ID of the avatar used in this chat',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'messages',
                    models.JSONField(
                        default=list,
                        help_text="Array of chat messages: [{role: 'user'|'assistant', content: '...', timestamp: '...'}]",
                    ),
                ),
                (
                    'score',
                    models.FloatField(
                        blank=True,
                        help_text='Overall score for this chat session based on user interactions',
                        null=True,
                    ),
                ),
                (
                    'interaction_count',
                    models.IntegerField(
                        default=0, help_text='Number of user messages in this chat'
                    ),
                ),
                (
                    'completed',
                    models.BooleanField(
                        default=False,
                        help_text='Whether the chat session is marked as completed',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'openwebui_chat_id',
                    models.CharField(
                        blank=True,
                        help_text='Reference to OpenWebUI chat ID if synced',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chats',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('user', 'User'),
                            ('assistant', 'Assistant'),
                            ('system', 'System'),
                        ],
                        max_length=20,
                    ),
                ),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                (
                    'chat',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_messages',
                        to='api.chat',
                    ),
                ),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(
                fields=['user', '-updated_at'], name='api_chat_user_id_295c9b_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(
                fields=['completed'], name='api_chat_complet_e9a310_idx'
            ),
        ),
    ]
