# Generated by Django 5.2.4 on 2025-10-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_chat_chatmessage_chat_api_chat_user_id_295c9b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(
                choices=[
                    ('ready', 'Ready'),
                    ('in_progress', 'In Progress'),
                    ('thinking', 'AI Thinking'),
                    ('ready_for_grading', 'Ready for Grading'),
                    ('grading', 'Being Graded'),
                    ('complete', 'Complete'),
                ],
                default='ready',
                help_text='Current status of the chat session',
                max_length=20,
            ),
        ),
    ]
