# Generated by Django 5.2.4 on 2025-10-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='grading_data',
            field=models.JSONField(
                blank=True,
                help_text='Complete grading response from LLM evaluator',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='chat',
            name='help_responses',
            field=models.JSONField(
                default=list,
                help_text="Array of help responses: [{turn: 1, timestamp: '...', help_text: '...'}]",
            ),
        ),
    ]
