# Generated by Django 5.2.4 on 2025-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_chat_grading_data_chat_help_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(
                choices=[
                    ('ready', 'Ready'),
                    ('in_progress', 'In Progress'),
                    ('thinking', 'AI Thinking'),
                    ('getting_help', 'Getting Help'),
                    ('ready_for_grading', 'Ready for Grading'),
                    ('grading', 'Being Graded'),
                    ('complete', 'Complete'),
                ],
                default='ready',
                help_text='Current status of the chat session',
                max_length=20,
            ),
        ),
    ]
